# Generated by Django 3.2.4 on 2021-07-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_alter_game_time_start_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
