# Generated by Django 3.2.4 on 2021-07-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_game_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='all_users',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='all_words',
            field=models.JSONField(default=[]),
        ),
    ]
