# Generated by Django 3.2.4 on 2021-07-09 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_remove_game_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='all_remaining_words',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='game',
            name='number_word',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='next_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start_round',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 15, 18, 33, 693535)),
        ),
    ]
