# Generated by Django 3.2.4 on 2021-07-09 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_auto_20210709_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='time_start_round',
            field=models.DateField(default=datetime.datetime(2021, 7, 9, 15, 36, 21, 680894)),
        ),
    ]
