# Generated by Django 3.2.4 on 2021-07-09 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_auto_20210709_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time_start_round',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 9, 15, 56, 29, 308686)),
        ),
    ]
