# Generated by Django 3.2.4 on 2021-07-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOperations', '0002_auto_20210701_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_user',
            name='all_games',
            field=models.JSONField(default=[]),
        ),
    ]
